name: "create-repository"
description: "Standardize github repository creation"
inputs:
  template:
    required: true
    description: "Kind of your new repository"
  template_path:
    required: false
    description: "Directory where all your template are stored"
    default: "."
  repo_name:
    required: true
    description: "Name of your new repository"
  repo_description:
    required: false
    description: "Description of your new repository"
    default: ""
  repo_is_private:
    required: false
    description: "Scope of your new repository"
    default: "false"
  repo_workflow_access:
    required: false
    description: "Modify workflow permission for the reposity"
    default: "false"
  github_token:
    required: true
    description: "Github token used to create the repository"
  personal_use:
    required: false
    description: "Define if repository will be created in a user profile (true) or a github org (false)"
    default: "false"
  delete_repo:
    required: false
    description: "For testing purpose it is useful to delete the repository after its creation"
    default: "false"
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "terminal"
  color: "green"
