name: 'create-repository'
description: 'Standardize github repository creation'
inputs:
  repo_name:
    required: true
    description: 'Name of your new repository'
  repo_template:
    required: true
    description: 'Kind of your new repository'
  github_token:
    required: true
    description: 'Github token used to create the repository'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'terminal'
  color: 'green'
