name: 'create-gh-action'
description: 'Standardize github action creation'
inputs:
  repo_name:
    required: true
    description: 'Name of your new action'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
    icon: "terminal"
    color: "green"