name: "Repository creator"
run-name: "Create repository [name: ${{ inputs.repository }}][template: ${{ inputs.template }}]"
on:
  workflow_dispatch:
    inputs:
      template:
        description: "Choose the kind of repository"
        required: true
        type: choice
        options:
          - action
      repository:
        description: "Name of your new repository"
        required: true
        type: string
      description:
        description: "Description of your new repository"
        required: false
        type: string
      is_private:
        description: "Select to make repository private"
        required: false
        type: boolean
      write_access_workflow:
        description: "Select to modify workflow access"
        required: false
        type: boolean

jobs:
  create-new-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
      - name: Formatting
        run: npm run format
      - name: Testing
        run: npm run test
      - name: Build
        run: npm run all
      - name: Test action
        uses: ./
        with:
          repo_name: ${{ inputs.repository }}
          repo_description: ${{ inputs.description}}
          repo_is_private: ${{ inputs.is_private }}
          repo_workflow_access: ${{ inputs.write_access_workflow }}
          template: ${{ inputs.template }}
          template_path: "tests/act/template_example"
          personal_use: true
          delete_repo: true
          github_token: ${{ secrets.GH_TOKEN }}
