name: "Repository creator"
run-name: "Create repository [name: ${{ inputs.repository }}][template: ${{ inputs.template }}]"
on:
  workflow_dispatch:
    inputs:
      template:
        description: "Choose the kind of repository"
        required: true
        type: choice
        options:
          - action
          - terraform
      repository:
        description: "Name of your new repository"
        required: true
        type: string
      description:
        description: "Description of your new repository"
        required: false
        type: string
      is_private:
        description: "Would you like your new repo to be private"
        required: false
        type: boolean

jobs:
  create-new-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
      - name: Formatting
        run: npm run format
      - name: Build
        run: npm run all
      - name: Create repository for new action
        uses: ./
        with:
          repo_name: ${{ inputs.repository }}
          repo_description: ${{ inputs.description}}
          repo_is_private: ${{ inputs.is_private }}
          template: ${{ inputs.template }}
          template_path: "tests/templates"
          personal_use: true
          github_token: ${{ secrets.GH_TOKEN }}
