name: "Verify formatting, tests and build process"
on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
      - name: Formatting
        run: npm run format
      - name: Testing
        run: npm run test
      - name: Build and compile
        run: npm run all
