name: "Repository creator"
run-name: "Create repository [name: ${{ inputs.repository }}][template: ${{ inputs.template }}]"
on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Name of your new repository"
        required: true
        type: string
      template:
        description: "Choose the kind of repository"
        required: true
        type: choice
        options:
          - action
          - terraform

jobs:
  create-new-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
      - name: Formatting
        run: npm run format
      - name: Build
        run: npm run all
      - name: Create repository for new action
        uses: ./
        with:
          personal_use: true
          github_token: ${{ secrets.GH_TOKEN }}
          repo_name: ${{ inputs.repository }}
          repo_template: ${{ inputs.template }}