name: "Release new version"
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Install node modules
        run: npm install
      - name: Build and compile
        run: npm run all
      - name: Tag repository
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch
      - name: Publish github release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            ## Changelog 
            ${{ steps.tag_version.outputs.changelog }}
          artifacts: "dist/index.js,action.yml,node_modules/*"
